### ISSUE TITLE
themes property default value not working, error received instead

### ISSUE THREAD

**Issue by mrnusa** [Iteo/theme_tailor#35]
Hi, 

if u not set the themes property:
`@Tailor(themes: ['light', 'dark'])`
just type this:
`@Tailor`
you will receive the following error message and the tailor file not generated:
`type 'Null' is not a subtype of type 'List<dynamic>' in type cast`

regards

**Comment by jackstefansky** [comment]
I am having the same problem :/

**Comment by Rongix** [comment]
Hey, sorry for the inconvenience, to temporarily use the branch with the fix add the following to your pubspec.yaml

```yaml
dev_dependencies:
  theme_tailor:
    git:
      url: https://github.com/Iteo/theme_tailor.git
      path: packages/theme_tailor
      ref: fix/#35
```
