### ISSUE TITLE
Feat: Add documentation to generated props

### ISSUE THREAD

**Issue by jtdLab** [Iteo/theme_tailor#54]
Is it possible to document the properties in the generated .tailor file?

For example 

```dart
@tailor
class _$BoxTheme {
  /// Some documentation foo bar
  static List<Color> backgroundColor = [
    Colors.red,
    Colors.blue,
  ];
}
```

should lead to

```dart
class BoxTheme extends ThemeExtension<BoxTheme> {
  const BoxTheme({
    required this.backgroundColor,
  });

  /// Some documentation foo bar
  final Color backgroundColor;

  /// ...
}
```

**Comment by Rongix** [comment]
Hey, thanks for the feature proposal, we've worked on this issue some time ago and it is pending for the next release
https://github.com/Iteo/theme_tailor/pull/51

If you want to try it now it's available on the develop branch:
```yaml
dev_dependencies:
  theme_tailor:
    git:
      url: https://github.com/Iteo/theme_tailor.git
      path: packages/theme_tailor
      ref: develop
```
