### ISSUE TITLE
Generating Flutter diagnosticable / debugFillProperties does not work in some cases

### ISSUE THREAD

**Issue by jtdLab** [Iteo/theme_tailor#68]
Generating Flutter diagnosticable / debugFillProperties works well in most cases.
But when having an other flutter import before the `package:flutter/foundation.dart`import like so:

```dart
import 'package:flutter/animation.dart'; // even import 'package:flutter/widgets.dart' or other flutter imports break it
import 'package:flutter/foundation.dart';
```

The  diagnosticable / debugFillProperties are not generated.

Hint: 
None flutter imports work fine:

```dart
import 'package:aaa:aaa.dart'; // or import 'package:zzz:zzz.dart'; work fine
import 'package:flutter/foundation.dart';
```

**Comment by Rongix** [comment]
Hey, here is a fix (#70) if you would like to use it right now, it should be merged later this month at the beginning of the next one (If you try it please let me know if it works for you, I've checked some other cases and I think that's all) 

###### pubspec.yaml
```yaml
theme_tailor:
  git:
    url: https://github.com/Iteo/theme_tailor.git
    path: packages/theme_tailor
    ref: theme_tailor/fix/diagnosticable-tree-mixin
```
