### ISSUE TITLE
Build runner issue 

### ISSUE THREAD

**Issue by marcosgcd** [Iteo/theme_tailor#85]
I don't know how the generating works in flutter but I think theme_tailor is looking at an annotation that it should not.

I get this error. 

<img width="1089" alt="Bildschirmfoto 2023-09-24 um 01 59 11" src="https://github.com/Iteo/theme_tailor/assets/137309939/86086011-a933-413c-a5cf-d4ce2a915b09">

If more info is required please let me know.

**Comment by Rongix** [comment]
Since Widgetbook is unfamiliar to me, it would be immensely helpful if you could provide a code sample to give us better context for your issue.

In the meantime, as a potential workaround, you might want to consider naming your relevant files with a distinctive pattern, something that can be filtered by the build runner (e.g.: "*.tailor.dart"). This could help restrict code generators to the specific files you intend.

```yaml
targets:
  $default:
    builders:
      theme_tailor:
        generate_for:
          include:
            - lib/**.tailor.dart
```
